language: cpp
os: linux

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../bld

#Stage Expansions
_configure: &configure
  before_script:
    - rm -rf ${TRAVIS_BUILD_DIR}/../bld
    - echo $PWD && mkdir ../bld && cd ../bld && echo $PWD
  script:
    - cmake ${TRAVIS_BUILD_DIR}


jobs:
  include:
    - stage: Configure
      dist: trusty
      <<: *configure
    - stage: Configure
      dist: precise    
      <<: *configure

    - stage: Build
      dist: trusty
      before_script: cd ../bld
      script:
        - make


    - stage: Test
      dist: trusty
      before_script: cd ../bld
      script:
        - ctest -VV
