language: cpp
os: linux
dist:
  - trusty
  - precise
  - xenial
  - bionic

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../bld

jobs:
  include:
    - stage: Configure
      before_script:
        - rm -rf ${TRAVIS_BUILD_DIR}/../bld
        - echo $PWD && mkdir ../bld && cd ../bld && echo $PWD
      script:
        - cmake ${TRAVIS_BUILD_DIR}
    - stage: Build
      before_script: cd ../bld
      script:
        - make
    - stage: Test
      before_script: cd ../bld
      script:
        - ctest -VV
