language: cpp

os: linux

addons:
  apt:
    packages:
    - cmake

script:
  - echo $PWD && ls -ahl && mkdir ../bld && cd ../bld && echo $PWD
  - cmake ${TRAVIS_BUILD_DIR}

# jobs:
#   include:
#     - stage: "Configure"
#       script:
#         - cmake ../ners570f20-Lab06
#     - stage: "Build"
#       script: make
#     - stage: "Test"
#       script:
#         - echo "NO TESTS YET!"
#     - stage: "Install"
#         - echo "NO INSTALL YET!"

