language: cpp
os: linux

jobs:
  include:
    - stage: config
      name: "Configure"
      script:
        - echo $PWD && mkdir ../bld && cd ../bld && echo $PWD
        - cmake ${TRAVIS_BUILD_DIR}
    - stage: build
      name:  "Build"
      script:
        - echo $PWD 
        - cd ../bld
        - make

