language: cpp
os: linux
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../bld

jobs:
  include:
    - stage: Configure
      before_script:
        - rm -rf ${TRAVIS_BUILD_DIR}/../bld
        - echo $PWD && mkdir ../bld && cd ../bld && echo $PWD
      script:
        - cmake ${TRAVIS_BUILD_DIR}
    - stage: Build
      script:
        - echo $PWD 
        - cd ../bld
        - make

